      MODULE GLOBAL
        PARAMETER(NIUNIT=100)
        integer,save,pointer::iunsat
        INTEGER,SAVE,POINTER ::NCOL,NROW,NLAY,NPER,NBOTM,NCNFBD,IVSD
        INTEGER, SAVE, POINTER ::ITMUNI,LENUNI,IXSEC,ITRSS,INBAS,IUNSTR
        INTEGER, SAVE, POINTER :: IDEALLOC_LPF,IDEALLOC_HY,ISYMFLG
        INTEGER, SAVE, POINTER :: ITRNSP,NEQS,NODES,NJA,NJAS,NJAG
        INTEGER, SAVE, POINTER :: IOUT,IPRCONN,IDSYMRD,ILAYCON4,IWADI,
     *    IWADICLN,IDPF,IDPT,INSGB, ImdT
        INTEGER, SAVE, POINTER :: INCLN,INGNC,INGNC2,INGNCn, INDDF
        INTEGER, SAVE, POINTER :: IFMBC,MBEGWUNF,MBEGWUNT,MBECLNUNF,
     *    MBECLNUNT
        INTEGER, SAVE,POINTER ::IFREFM,MXNODLAY,NOCVCO,ICONCV,NOVFC
        DOUBLE PRECISION, SAVE, POINTER::WADIEPS
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::IUNIT(:)
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::IBOUND
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::IA
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::IAG
        REAL*8, DIMENSION(:),ALLOCATABLE  :: FLOWJA(:),FMBE(:)
        INTEGER, POINTER, DIMENSION(:) :: IATMP
        INTEGER, POINTER :: NJATMP
        INTEGER, SAVE,    DIMENSION(:), POINTER  ::JA
        INTEGER, SAVE,    DIMENSION(:), POINTER ::JAFL          
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::JAS
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::ISYM
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::IVC
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::HOLD
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::HNEW
        DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE ::RHS
        DOUBLE PRECISION, SAVE, DIMENSION(:), POINTER ::AMAT
        DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE ::Sn,So
        DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE ::AKRC,AKR
        DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE ::TURBGRAD
        REAL, DIMENSION(:),ALLOCATABLE  ::DELR
        REAL, DIMENSION(:),ALLOCATABLE  ::DELC
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::BOT
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::TOP
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::PGF
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::AREA
        REAL, SAVE, DIMENSION(:),ALLOCATABLE  ::FAHL        
        REAL, SAVE, DIMENSION(:),ALLOCATABLE  ::CL1,CL2
        REAL, SAVE, DIMENSION(:),ALLOCATABLE  ::ARAD
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::NODLAY
        INTEGER, SAVE,  ALLOCATABLE,   DIMENSION(:)     ::LAYNOD
        INTEGER, DIMENSION(:),    ALLOCATABLE  ::LAYCBD
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::LAYHDT
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::LAYHDS
        DOUBLE PRECISION,  SAVE, DIMENSION(:),  ALLOCATABLE  ::PERLEN
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::NSTP
        REAL,    SAVE,    DIMENSION(:),    ALLOCATABLE  ::TSMULT
        INTEGER, SAVE,    DIMENSION(:),    ALLOCATABLE  ::ISSFLG
        REAL,    SAVE,    DIMENSION(:),ALLOCATABLE  ::BUFF
        REAL,    SAVE,    DIMENSION(:), POINTER  ::STRT
        DOUBLE PRECISION,  SAVE,  ALLOCATABLE,   DIMENSION(:) ::HWADI
        DOUBLE PRECISION,  SAVE,  ALLOCATABLE,   DIMENSION(:) ::DWADI
        REAL,    SAVE,    DIMENSION(:), POINTER ::DDREF
        INTEGER,           SAVE, DIMENSION(:),  ALLOCATABLE ::NODETIBH
        INTEGER, POINTER :: NIB1
        DOUBLE PRECISION, SAVE, DIMENSION(:),ALLOCATABLE  ::HTIB
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::IA2
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::JA2
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::IA1IA2
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::JA1JA2
        INTEGER, SAVE, POINTER :: NEQS2,NJA2
      END MODULE GLOBAL
C
C -----------------------------------------------------------------------
      MODULE PARAMMODULE
C  Data definitions for Named Parameters
C  Explicitly declare all variables to enable subroutines that include
C  this file to use the IMPLICIT NONE statement.
        PARAMETER (MXPAR=999,MXCLST=1000,MXINST=1000)
        INTEGER,SAVE,POINTER ::ICLSUM,IPSUM,INAMLOC,NMLTAR,NZONAR,NPVAL
        REAL,          SAVE,    DIMENSION(:),    ALLOCATABLE ::B
        INTEGER,       SAVE,    DIMENSION(:),    ALLOCATABLE ::IACTIVE
        INTEGER,       SAVE,    DIMENSION(:,:),  ALLOCATABLE ::IPLOC
        INTEGER,       SAVE,    DIMENSION(:,:),  ALLOCATABLE ::IPCLST
        INTEGER,       SAVE,    DIMENSION(:,:,:),ALLOCATABLE ::IZON
        REAL,          SAVE,    DIMENSION(:,:,:),ALLOCATABLE ::RMLT
        CHARACTER(LEN=10),SAVE, DIMENSION(:),    ALLOCATABLE ::PARNAM
        CHARACTER(LEN=4), SAVE, DIMENSION(:),    ALLOCATABLE ::PARTYP
        CHARACTER(LEN=10),SAVE, DIMENSION(:),    ALLOCATABLE ::ZONNAM
        CHARACTER(LEN=10),SAVE, DIMENSION(:),    ALLOCATABLE ::MLTNAM
        CHARACTER(LEN=10),SAVE, DIMENSION(:),    ALLOCATABLE ::INAME
      END MODULE PARAMMODULE
C
C -----------------------------------------------------------------------
      MODULE GWFBASMODULE
        INTEGER, SAVE, POINTER  ::MSUM
        INTEGER, SAVE, POINTER  ::IHEDFM,IHEDUN,IDDNFM,IDDNUN,IBOUUN,
     *    ISPCFM,ISPCUN
        INTEGER, SAVE, POINTER  ::LBHDSV,LBDDSV,LBBOSV
        INTEGER, SAVE, POINTER  ::IBUDFL,ICBCFL,IHDDFL,ISPCFL,
     *   IAUXSV,IBDOPT,IATS,IBUDFLAT,ICBCFLAT,IHDDFLAT,ISPCFLAT
        INTEGER, SAVE, POINTER :: IFAST,ISPFAST,ITSFAST,IUGFAST,IUCFAST,
     *    IUDFAST,IFASTH,IFASTC,ISPFASTC,ITSFASTC,IUGFASTC,IUCFASTC,
     *    IUDFASTC,IUMFASTC  
        INTEGER, SAVE, POINTER  ::IPRTIM,IPEROC,ITSOC,ICHFLG,IFRCNVG
        DOUBLE PRECISION,  SAVE, POINTER  ::DELT,PERTIM,TOTIM
        DOUBLE PRECISION, SAVE, POINTER :: DELTAT,TMINAT,TMAXAT,TADJAT,
     1        TCUTAT
        INTEGER, SAVE, POINTER ::NPTIMES,NPSTPS,ITIMOT
        DOUBLE PRECISION,  SAVE, DIMENSION(:),ALLOCATABLE  ::TIMOT
        REAL,              SAVE, POINTER  ::HNOFLO
        CHARACTER(LEN=20), SAVE, POINTER   ::CHEDFM,CDDNFM,CBOUFM,CSPCFM
        INTEGER,           SAVE, DIMENSION(:,:), ALLOCATABLE ::IOFLG
        DOUBLE PRECISION,  SAVE, DIMENSION(:,:), ALLOCATABLE ::VBVL
        CHARACTER(LEN=16), SAVE, DIMENSION(:),   ALLOCATABLE ::VBNM
        INTEGER, SAVE, POINTER  ::IDDREF,IDDREFNEW
      END MODULE GWFBASMODULE
C
C -----------------------------------------------------------------------
      MODULE GWFBCFMODULE
       INTEGER,SAVE,POINTER::IBCFCB,IWDFLG,IWETIT,IHDWET,IKCFLAG,
     1  IKVFLAG,IBPN,IDRY,ITABRICH,INTRICH,NUTABROWS,NUZONES 
       REAL, SAVE, POINTER    ::WETFCT,HDRY
       INTEGER, SAVE,  ALLOCATABLE,   DIMENSION(:)     ::LAYCON
       INTEGER, SAVE,  ALLOCATABLE,   DIMENSION(:)     ::LAYAVG,LAYAVGV
       REAL, SAVE,     ALLOCATABLE,   DIMENSION(:) ::CV
       REAL, SAVE,     ALLOCATABLE,   DIMENSION(:) ::SC1
       REAL, SAVE,     ALLOCATABLE,   DIMENSION(:) ::SC2
       REAL, SAVE,     ALLOCATABLE,   DIMENSION(:) ::WETDRY
       REAL, SAVE,  ALLOCATABLE,   DIMENSION(:) ::alpha,beta,sr,brook,BP
       INTEGER, SAVE, ALLOCATABLE, DIMENSION(:) :: IUZONTAB
       REAL, SAVE, ALLOCATABLE, DIMENSION(:,:,:) :: RETCRVS
       INTEGER, SAVE,   ALLOCATABLE, DIMENSION(:)     ::LAYWET
C
        INTEGER, SAVE,   POINTER ::ISFAC,ITHFLG,IHANISO,IALTSTO
        INTEGER, SAVE,   ALLOCATABLE, DIMENSION(:)     ::LAYTYP
        REAL,    SAVE,   ALLOCATABLE, DIMENSION(:)     ::CHANI
        INTEGER, SAVE,   ALLOCATABLE, DIMENSION(:)     ::LAYVKA
        INTEGER, SAVE,   ALLOCATABLE, DIMENSION(:)     ::LAYSTRT
        INTEGER, SAVE,   ALLOCATABLE, DIMENSION(:,:)   ::LAYFLG
        REAL,    SAVE,   ALLOCATABLE, DIMENSION(:) ::VKA
        REAL,    SAVE,   ALLOCATABLE, DIMENSION(:) ::VKCB
        REAL,    SAVE,   ALLOCATABLE, DIMENSION(:) ::HANI
        REAL,    SAVE,   ALLOCATABLE, DIMENSION(:) ::HK
        DOUBLE PRECISION,  SAVE,  ALLOCATABLE,  DIMENSION(:) :: HWADIGW 
        DOUBLE PRECISION,  SAVE,  ALLOCATABLE,  DIMENSION(:) :: DWADIGW
      END MODULE GWFBCFMODULE
C -------------------------------------------------------------------------------------
      MODULE CLN1MODULE
        INTEGER, SAVE,POINTER :: NCLN,ICLNCB,ICLNHD,ICLNDD,ICLNIB,
C    1           NJA_CLN, NCLNNDS,NCLNGWC,NCONDUITYP,NRECTYP,            !aq CLN CCF
     1           NJA_CLN, NCLNNDS,NCLNGWC,NCONDUITYP,NRECTYP,ICLNTIB,    !aq CLN CCF
     2           ICLNPCB,ICLNGWCB,                                       !aq CLN CCF
     1           ICLNCN,ICLNMB,IBHETYP
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::NNDCLN
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::IFLINCLN
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::ICCWADICLN
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::ICGWADICLN
        INTEGER, SAVE,    DIMENSION(:),ALLOCATABLE  ::CLNCON
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::IA_CLN
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::JA_CLN
        INTEGER, SAVE,    DIMENSION(:),POINTER  ::IDXGLO_CLN
        DOUBLE PRECISION, SAVE,    DIMENSION(:,:),ALLOCATABLE  ::ACLNNDS
        REAL, SAVE,    DIMENSION(:,:),ALLOCATABLE  ::ACLNGWC
        DOUBLE PRECISION, SAVE,   DIMENSION(:,:),ALLOCATABLE  ::ACLNCOND
        REAL, SAVE,    DIMENSION(:,:),ALLOCATABLE  :: BHEPROP
         REAL, SAVE,    DIMENSION(:,:),ALLOCATABLE  ::ACLNREC
C-------FOR FLOW TO DRY CELL FORMULATION        
        DOUBLE PRECISION,  SAVE, ALLOCATABLE,  DIMENSION(:) ::HWADICC
        DOUBLE PRECISION,  SAVE, ALLOCATABLE,  DIMENSION(:) ::HWADICG
        DOUBLE PRECISION,  SAVE, ALLOCATABLE,  DIMENSION(:) ::DWADICC
        DOUBLE PRECISION,  SAVE, ALLOCATABLE,  DIMENSION(:) ::DWADICG
C-------FOR TURBULENT FLOW FORMULATION 
        REAL, SAVE, POINTER :: GRAV, VISK
        
      END MODULE CLN1MODULE
C
C -------------------------------------------------------------------------------------
      MODULE SMSMODULE
      IMPLICIT NONE
      DOUBLE PRECISION, PARAMETER :: EPSILON = 1.0E-6
      DOUBLE PRECISION, PARAMETER :: CLOSEZERO = 1.0E-15      
      DOUBLE PRECISION, SAVE, POINTER :: Theta
      DOUBLE PRECISION, SAVE, POINTER :: Akappa, Gamma, Amomentum,
     *  Breduc, Btol,RES_LIM
      DOUBLE PRECISION, SAVE, DIMENSION(:), POINTER ::AMATFL
      DOUBLE PRECISION, SAVE, POINTER :: HCLOSE, HICLOSE,BIGCHOLD,BIGCH
      INTEGER, SAVE, POINTER :: ITER1,MXITER,LINMETH,NONMETH,Numtrack,
     *  IPRSMS,IBFLAG     
      DOUBLE PRECISION, DIMENSION(:),ALLOCATABLE  :: CELLBOTMIN
      DOUBLE PRECISION, DIMENSION(:),ALLOCATABLE  ::HTEMP
CSP - THIS IS AMAT      DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: A
CSP - THIS IS RHS      DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: B
CSP - THIS IS HNEW      DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: Hchange
      INTEGER, SAVE, DIMENSION(:,:), ALLOCATABLE ::  Lrch
      INTEGER, SAVE, DIMENSION(:), ALLOCATABLE ::  LrchL
      DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: Hncg
      DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE ::  HNCGL
      DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: DKDH,DKDHC
      DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: DTURBGRAD
      DOUBLE PRECISION,SAVE,DIMENSION(:),ALLOCATABLE::DEold,Wsave,Hchold
      INTEGER ISOLVEACTIVE, IBOTAV,ISHIFT
      double precision scalfact
      ! DM: Forcing term variables
      DOUBLE PRECISION, SAVE, POINTER::Rcutoff,ForcingAlpha,ForcingGamma
      DOUBLE PRECISION, SAVE, POINTER::MaxRcutoff
      INTEGER, SAVE, POINTER      ::ICUTOFF,NoMoreRcutoff,ITRUNCNEWTON
      ! End DM
      END MODULE SMSMODULE
C------------------------------------------------------------------
      MODULE TVMU2MODULE
          INTEGER,SAVE :: ITVMPRINT,NTVMHK,NTVMVKA,NTVMSS,NTVMSY,NTVMPOR
          INTEGER,SAVE :: NTVMSCHANGES
          INTEGER,SAVE :: NTVMDDFTR
          INTEGER,SAVE :: IHAVESC2
          INTEGER,SAVE,ALLOCATABLE,DIMENSION(:) :: ITVMHK,ITVMVKA
          INTEGER,SAVE,ALLOCATABLE,DIMENSION(:) :: ITVMSS,ITVMSY
          INTEGER,SAVE,ALLOCATABLE,DIMENSION(:) :: ITVMPOR
          INTEGER,SAVE,ALLOCATABLE,DIMENSION(:) :: ITVMDDFTR
          REAL,SAVE :: TVMLOGBASEHK,TVMLOGBASEHKINV
          REAL,SAVE :: TVMLOGBASEVKA,TVMLOGBASEVKAINV
          REAL,SAVE :: TVMLOGBASESS,TVMLOGBASESSINV
          REAL,SAVE :: TVMLOGBASESY,TVMLOGBASESYINV
          REAL,SAVE :: TVMLOGBASEPOR,TVMLOGBASEPORINV
          REAL,SAVE :: TVMDDFTR,TVMDDFTRINV
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: HKNEWA,VKANEWA
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: HKNEWB,VKANEWB
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: SSNEWA,SYNEWA
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: SSNEWB,SYNEWB
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: SSOLD,SYOLD
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: PORNEWA
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: PORNEWB
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: POROLD
          REAL,SAVE,ALLOCATABLE,DIMENSION(:) :: DDFTRNEWA,DDFTRNEWB
          INTEGER,SAVE,ALLOCATABLE,DIMENSION(:) :: ITVMSMAPSS
          INTEGER,SAVE,ALLOCATABLE,DIMENSION(:) :: ITVMSMAPSY
          INTEGER,SAVE,ALLOCATABLE,DIMENSION(:) :: ITVMSMAPPOR
          DOUBLE PRECISION,SAVE,ALLOCATABLE,DIMENSION(:) :: INITPGF
      END MODULE
C
C -------------------------------------------------------------------------------------      
      MODULE GWTBCTMODULE
       INTEGER,SAVE,POINTER::IBCTCB,MCOMP,ITVD,IADSORB,ICT,NTITER,IDISP,
     *   IXDISP,IZOD,IFOD,IHEAT,MCOMPT,NTCOMP,IDISPCLN,IMULTI,NSEQITR,
     *   ISOLUBILITY
       REAL, SAVE, POINTER    ::CINACT
       DOUBLE PRECISION, SAVE, POINTER ::CICLOSE
       REAL, SAVE, POINTER ::DIFFNC
       INTEGER, SAVE, DIMENSION(:,:), ALLOCATABLE ::  LrcC
       INTEGER,    SAVE, DIMENSION(:), ALLOCATABLE     ::IPCBFLAG
       DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: Cncg
       INTEGER, SAVE,  ALLOCATABLE,   DIMENSION(:)     ::ICBUND
       REAL, SAVE,     ALLOCATABLE,   DIMENSION(:) ::PRSITY
       DOUBLE PRECISION, SAVE,     ALLOCATABLE,   DIMENSION(:) ::MASSBCT
       REAL, SAVE, ALLOCATABLE,   DIMENSION(:,:) ::ADSORB,FLICH,
     1  ZODRW,FODRW,ZODRS,FODRS
       REAL, SAVE, ALLOCATABLE,   DIMENSION(:,:) ::VELNOD
       REAL, SAVE, ALLOCATABLE,  DIMENSION(:) :: DLX,DLY,DLZ,
     1   ATXY,ATYZ,ATXZ
       REAL, SAVE, ALLOCATABLE,  DIMENSION(:) :: ALXY,ALYZ,ALXZ
       DOUBLE PRECISION, SAVE,  ALLOCATABLE,DIMENSION(:,:) ::CONC,CONCO
       REAL*8, SAVE,     ALLOCATABLE,   DIMENSION(:) ::CBCF
       REAL, SAVE,     ALLOCATABLE,   DIMENSION(:) ::CBCH
       DOUBLE PRECISION,    SAVE, DIMENSION(:,:,:), ALLOCATABLE ::VBVLT
       CHARACTER(LEN=16), SAVE, DIMENSION(:,:),   ALLOCATABLE ::VBNMT
       INTEGER, SAVE, POINTER  ::MSUMT
       INTEGER, SAVE, DIMENSION(:), ALLOCATABLE ::  FLrcC
       DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: FCncg
       DOUBLE PRECISION, SAVE, DIMENSION(:), ALLOCATABLE :: ADMAT
       REAL, SAVE,     ALLOCATABLE,   DIMENSION(:) ::DXCS,DYCS,DZCS
       INTEGER,           SAVE, DIMENSION(:),  ALLOCATABLE ::NODETIBC
       INTEGER, POINTER :: NICB1
       DOUBLE PRECISION, SAVE, DIMENSION(:,:),ALLOCATABLE  ::CTIB
       REAL, SAVE, POINTER :: HTCONDW, RHOW, HTCAPW 
       REAL, SAVE, ALLOCATABLE, DIMENSION(:) :: HTCONDM, HTCONDS,HTCONDT
       CHARACTER (LEN=200), SAVE :: CROOTNAME
       DOUBLE PRECISION, SAVE, POINTER :: TIMEWEIGHT
       INTEGER, SAVE, POINTER :: ICHAIN,ISPRCT
       INTEGER, SAVE,  ALLOCATABLE,   DIMENSION(:) :: NPARENT
       INTEGER, SAVE,  ALLOCATABLE,   DIMENSION(:,:) :: JPARENT
       REAL, SAVE, ALLOCATABLE, DIMENSION (:,:) :: STOTIO
       REAL, SAVE, ALLOCATABLE, DIMENSION (:,:,:) :: SPTLRCT
       REAL, SAVE, ALLOCATABLE,   DIMENSION(:) :: SOLLIM, SOLSLOPE
      END MODULE GWTBCTMODULE
